### ISSUE TITLE
App in a Term::ReadLine loop

### ISSUE THREAD

**Issue by wols** [maros/MooseX-App#36]
Hi, I have my first app with a first command and it runs from script `myapp` via `MyApp->new_with_command->run();` fine.

I would write a second `myapp-cli` like:
```perl
    while ( defined ( Term::ReadLine::Event->with_AnyEvent()->readline($prompt) ) ) {
        say $OUT $_; # DEBUG

        # here should MyApp->new_with_command()->run with subcommands and options in $_
        # but a simple
        MyApp->new_with_command->run($_);
        # is not well
        # and last the while loop ist not what I want...
    }
```
Thank you for a tipp!

**Comment by maros** [comment]
Please have a look at MooseX::App::ParsedArgv. This is the class that parses and stores @ARGV. Since it is implemented as a singleton (and built only once per process) you need to reset the singleton and construct a new instance for each loop iteration.

Hope this helps. Please re-open the issue if you have further questions
